# Generated by Django 6.0.7 on 2026-07-31 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('rentals', '0006_rename_return_date_rental_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rental'),
        ),
    ]
