# Generated by Django 6.0.7 on 2026-07-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Fuel', 'Fuel'), ('Service', 'Service'), ('Spare Parts', 'Spare Parts'), ('Salary', 'Salary'), ('Electricity', 'Electricity'), ('Office', 'Office'), ('Other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
