# Generated by Django 6.0.7 on 2026-07-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
    ]
