# Generated by Django 6.0.7 on 2026-07-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_remaining_amount_rental_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='damage_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='deposit_refund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='late_fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
