# Generated by Django 6.0.7 on 2026-07-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rental_damage_charge_rental_deposit_refund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
