# Generated by Django 6.0.7 on 2026-07-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rental_expected_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='return_date',
            new_name='actual_return_date',
        ),
        migrations.AlterField(
            model_name='rental',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rental',
            name='daily_rent',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rental',
            name='damage_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rental',
            name='deposit_refund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rental',
            name='late_fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rental',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
