# Generated by Django 6.0.7 on 2026-07-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rename_return_date_rental_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='actual_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='expected_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rent_date',
            field=models.DateTimeField(),
        ),
    ]
