# Generated by Django 6.0.7 on 2026-08-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_alter_rental_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='extra_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rental',
            name='extra_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
