# Generated by Django 6.0.7 on 2026-08-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_rental_extra_charge_rental_extra_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='manual_extra_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rental',
            name='extra_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
