# Generated by Django 6.0.7 on 2026-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_rental_manual_extra_charge_alter_rental_extra_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='extra_charge',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='extra_hours',
        ),
        migrations.AlterField(
            model_name='rental',
            name='manual_extra_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
