# Generated by Django 6.0.7 on 2026-08-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_remove_rental_extra_charge_remove_rental_extra_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rental_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')], default='Daily', max_length=20),
        ),
    ]
