# Generated by Django 6.0.7 on 2026-07-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('aadhaar_number', models.CharField(max_length=20)),
                ('driving_license', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
