# Generated by Django 6.0.7 on 2026-07-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('daily_rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Service', 'Service')], default='Available', max_length=20)),
            ],
        ),
    ]
