# Generated by Django 6.0.7 on 2026-07-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'ordering': ['registration_number'], 'verbose_name': 'Bike', 'verbose_name_plural': 'Bikes'},
        ),
    ]
